### ISSUE TITLE
Prototype scrapping and dumping text from urls

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#142]
When creating bookmarks JSoup was used grab the title of the page [jsoup-line](https://github.com/R-Sandor/FindFirst/blob/3e532b76f8f679e54e45098e3e3a49e3be694068/server/src/main/java/dev/findfirst/core/service/BookmarkService.java#L126). It is possible to get all the text as well but raw text includes unrelated data from any adverts and or footers on the page. 

- [ ] As a sample experiment attempt to use the bookmarks from the [sampleData](https://github.com/R-Sandor/FindFirst/tree/main/sampleData). 
- [ ] Create an OpenSearch/Elastic Search cluster (These files may help). 
  - https://github.com/R-Sandor/FindFirst-ImageSearch/tree/main/docker-compose.yml
    - Removing the frontend in that yaml, and backend services. 
  - https://github.com/R-Sandor/FindFirst-ImageSearch/blob/main/.env
- [ ] Import the data
- [ ] Queries
  - Elastic search has a lot of ways to rank results so this may be a little tricky too.
