### ISSUE TITLE
[Frontend] able to edit my bookmarks

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#27]
# Details 
As a user I would like to be able to press an edit button and edit the title or other details like scrapable, and save the change.

## Tasks
- [x] Change the title of the bookmark
- [x] Save to server.

- [x] Add endpoint to take a bookmark's existing ID with a new Title
