### ISSUE TITLE
[Server] - BookmarkController.java /api/bookmark/import check file type and size

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#278]
# Details 
Currently the end point trusts that user is providing a legitimate HTML file that is not too large and is in fact an html file. 

# Tasks 
- [ ] Ensure HTML file does not exceed to 250Mb
- [ ] Check the file extension is `.html`
- [ ] A contents check to ensure that the file is a properly formatted HTML file.
- [ ] Add Unit tests for the new functionality.

**Comment by shravya-chepa** [comment]
Hey, can I work on this?

**Comment by R-Sandor** [comment]
@shravya-chepa Absolutely! Thank you :rocket:

**Comment by R-Sandor** [comment]
@shravya Are you still working on this?

**Comment by crypto-a** [comment]
@R-Sandor I can work on this if its not assigned to anyone

**Comment by R-Sandor** [comment]
@crypto-a Thanks, its all yours!

**Comment by crypto-a** [comment]
@R-Sandor I’ve completed the code, but I ran into an issue during testing. When I tried a file larger than 250 Mb, I got a broken pipe error that I haven’t handled.

Do you think I should increase the request size cap to 250 Mb, or should we stick to the current limit? Just want to confirm the design direction before I make any changes.

I’ve attached the error logs for reference. Thanks for your help!

[dev.findfirst.core.controller.BookmarkControllerTest.html.zip](https://github.com/user-attachments/files/18287905/dev.findfirst.core.controller.BookmarkControllerTest.html.zip)

**Comment by crypto-a** [comment]
I think I fixed it!!!!
