### ISSUE TITLE
[Server] - Search By Bookmark Title

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#280]
# Details 
There is a scafolded function in src/main/java/dev/findfirst/core/controller/SearchController.java`: 
```
@GetMapping("/api/search/title")
  public ResponseEntity<List<BookmarkDTO>> bookMarkSearchByTitle(
      @Valid @RequestBody SearchBkmkByTitleReq searchBkmkByTitleReq) {
    // GH ISSUE #280
    return new Response<>(List.of(new BookmarkDTO(0, null, null, null, false, null, null, null)),
        HttpStatus.OK).get();
  }
```

Given that titles often contain multiple keywords it would be ideal to be able to match only bookmarks that contain one or many of those keywords. 

We won't get too fancy with the search here such as ranking the results, or applying order of word algorithms as in the near future we will bring in a true search engine to FindFirst such as TypeSense, ElasticSearch, Meilisearch.

## Tasks 
- [x] Create a fuzzy search function in BookmarkJDBCRepository.
- [x] Add response entity return of BookmarkDTOs that contain the users search keywords.
- [x] Add unit tests using TestContainers to flex the SearchController.
  - Use the `BookmarkControllerTest.java` as an example of how to leverage TestContainesrs and perform sign in.
