### ISSUE TITLE
[Server] - add endpoint for updating bookmarks

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#283]
# Details 
As a user I would like to be able to edit a bookmark.

## Tasks 
- [x] Create an update end point in the bookmark controller. 
- [x] Validate the users' data in the request. 
- [x] Find the bookmark entity then update the fields and save.
