### ISSUE TITLE
[Server] - Fix export bug

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#287]
# Details
When the user attempts to export their bookmarks none of the links are present on the resulting html file. 

## Tasks 
- [ ] Investigate ExportBookmark.java 
- [ ] Create a couple of bookmarks or use the test user's account jsmith/test 
- [ ] Hit the export button in the browser or use curl/Postman to hit /bookmark/export endpoint. 
- [ ] Apply changes to fix bug 
- [ ] Add unit tests

**Comment by crypto-a** [comment]
Hello, I would like to work on this if possible
