### ISSUE TITLE
[Frontend] - Create a responsive view React Hook

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#288]
# Details
While working on some design options for the TagList in mobile/small screen mode I realized that the menu style toggle doesn't make sense in that layout. It makes more sense to just remove it in mobile views. 

This ticket is to give #289 support to solve that problem.

## Task
- [ ] Create a way to query the window size and to check for when the window resizes.
- [ ] https://blog.logrocket.com/developing-responsive-layouts-with-react-hooks/
- [ ] Vitest unit tests.

**Comment by Abhinav-softsensor** [comment]
Hi there,

I'm interested in working on this issue . I have experience with Frontend and would like to contribute to this project. Is this issue still available for assignment?

If so, I'd be happy to take it on. Could you please provide any additional context or guidelines I should be aware of before starting?

Thank you,
Abhinav

**Comment by R-Sandor** [comment]
@Abhinav-softsensor The issue can be all yours :+1: 

Nope, I would just recommend reviewing the [Dev guide](https://github.com/R-Sandor/FindFirst/blob/be20f09ccbda50ea434bb2e70ba4590e7ffe183e/docs/README.dev.md)

I want to use this issue so we can make the app little more responsive and have some components that when the screen gets too small we either don't show it or have a customized component.

**Comment by Abhinav-softsensor** [comment]
Not able to use the test account credentials jsmith:test , basically when i click on login , Javascript Prompt box opened and asked for credentials again , i also tried to make new Signup with my own credentials and again same problem

**Comment by Abhinav-softsensor** [comment]
<img width="280" alt="Screenshot 2025-01-14 210003" src="https://github.com/user-attachments/assets/7fe8cf59-bd11-4212-a366-4bd66b5a82fa" />
i was just testing FindFirst and sorry to ask but "Could you please point out which specific element in the image is the 'menu style toggle' that needs to be removed in mobile views?"

**Comment by R-Sandor** [comment]
The are just under the search bar is a list of tags, and whits not terrible unmanageable for a couple of tags, the situation becomes worse as more tags are added. We do have a ticket for this: #289 

![image](https://github.com/user-attachments/assets/064c5595-4ad3-4107-be96-c1a13047102a)
I know when I visit a page I don't want to get his with menulist that big, do you?

**Comment by R-Sandor** [comment]
@Abhinav-softsensor I have attached a link from Log Rocket that details an implementation:
https://blog.logrocket.com/developing-responsive-layouts-with-react-hooks/ 
Optimizing performance with a Context
