### ISSUE TITLE
[Frontend] - When the screen is too small don't render TagList

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#289]
# Details 
When the application is in mobile view or small screens do not render the TagList. The list become too large.

## Dependencies (i.e. do this first or wait...)
- [ ] needs R-Sandor/FindFirst#288 

## Tasks
- [ ] When the screen is mobile/sized don't render the TagList. 
- [ ] Use the view port React Hook.
