### ISSUE TITLE
[Frontend] - Create unit tests for /pages/api/screenshot/[screenshots].ts

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#291]
# Details 
We added an NextJS api route for serving images from the NextJS backend. But we have no code coverage.

## Tasks
- [ ] Create a new directory under `__tests__/api/screenshot.test.tsx`
- [ ] Mock the process.env.NEXT_PUBLIC_ IMAGE_DIR to use the test images 
  - i.e. ../data/test-screenshots/
  - vi.stubEnv('NEXT_PUBLIC_ IMAGE_DIR', '<PATH>')
- [ ] Add more images if necessary. 
- [ ] Create an img tag, or fetch that will trigger the api. 
  -  `/api/screenshot/filename-here.png
